function [x,fval,exitflag,output,population,score] = o_CA_Position_Objective_optim_ga(conf,...
    problem,lb,ub,PopulationSize_Data,EliteCount_Data,CrossoverFraction_Data,...
    MaxGenerations_Data,MaxStallGenerations_Data,FunctionTolerance_Data)
%% This is an auto generated MATLAB file from Optimization Tool.
% Copyright 2017  The MathWorks, Inc.
%% Start with the default options
options = optimoptions('ga');
%% Modify options setting
options = optimoptions(options,'PopulationSize', PopulationSize_Data);
options = optimoptions(options,'EliteCount', EliteCount_Data);
options = optimoptions(options,'CrossoverFraction', CrossoverFraction_Data);
%options = optimoptions(options,'NonlinearConstraintAlgorithm', 'auglag'); % 'penalty'
options = optimoptions(options,'MaxGenerations', MaxGenerations_Data);
options = optimoptions(options,'FunctionTolerance', FunctionTolerance_Data);
options = optimoptions(options,'MaxStallGenerations', MaxStallGenerations_Data);
options = optimoptions(options,'Display', 'off');
if conf.verbosity >= 1
    options = optimoptions(options,'PlotFcn', {@gaplotbestf,@gaplotstopping});
end
options = optimoptions(options,'UseParallel', true);
nvar = numel(lb); % == numel(ub) == num. variables in the gen
if strcmp(conf.genStructure, 'nchoosek')
    integervars = 1;
    if conf.multiPath
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_multipath(x,conf,problem),...
        nvar,[],[],[],[],lb,ub,@(x)o_all_NonLinear_Constraints(x,conf,problem),...
        integervars,options);
    else
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_singlepath(x,conf,problem),...
        nvar,[],[],[],[],lb,ub,@(x)o_all_NonLinear_Constraints(x,conf,problem),...
        integervars,options);
    end
elseif strcmp(conf.genStructure, 'allAntennas')
    options = optimoptions(options,'CrossoverFcn',...
        @(p,o,n,z1,z2,t)o_crossoverArrayGA(p,o,n,z1,z2,t,problem,conf));
    options = optimoptions(options,'MutationFcn',...
        @(p,o,n,z1,z2,z3,t)o_mutationArrayGA(p,o,n,z1,z2,z3,t,problem,conf));
    options = optimoptions(options,'CreationFcn',...
        @(g,f,o)o_creationArrayGA(g,f,o,problem,conf));
    if conf.multiPath
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_multipath(x,conf,problem),...
        nvar,[],[],[],[],[],[],[],[],options);
    else
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_singlepath(x,conf,problem),...
        nvar,[],[],[],[],[],[],[],[],options);
    end
else
    %integervars = 1:problem.Nmax;
    options = optimoptions(options,'CrossoverFcn',...
        @(p,o,n,z1,z2,t)o_crossoverArrayGA(p,o,n,z1,z2,t,problem,conf));
    options = optimoptions(options,'MutationFcn',...
        @(p,o,n,z1,z2,z3,t)o_mutationArrayGA(p,o,n,z1,z2,z3,t,problem,conf));
    options = optimoptions(options,'CreationFcn',...
        @(g,f,o)o_creationArrayGA(g,f,o,problem,conf));
    if conf.multiPath
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_multipath(x,conf,problem),...
        nvar,[],[],[],[],[],[],[],... % @lb,ub,(x)o_all_NonLinear_Constraints(x,conf,problem)
        [],options); %integervars,options);
    else
        [x,fval,exitflag,output,population,score] = ...
        ga(@(x)o_Position_Objective_optim_cost_singlepath(x,conf,problem),...
        nvar,[],[],[],[],[],[],[],... % lb,ub,@(x)o_all_NonLinear_Constraints(x,conf,problem),...
        [],options); %integervars,options);
    end
end